README.md
internal/cmd/list.go

- Fix a bunch of typos
- Explain the usage basics
- Add a note about config requirement

docs: slight improvement of the README

---

internal/cache/cache.go
internal/cmd/list.go
internal/config/config.go
internal/config/rule.go
internal/gh/gh.go
internal/notifications/notifications.go

Simplifies the handling and preserve order.

refactor: remove NotificationMap

---

internal/cache/cache.go
internal/gh/gh.go

This remove the cache dependency on notifications, and will accept any type

feat: make the cache more generic

---

internal/cmd/repl.go

refactor: use native bubbletea help and keybinding

---

internal/config/config.go
internal/jq/jq.go
internal/notifications/notifications.go
internal/notifications/notifications_test.go

refactor: rename DeleteNil and ToInterface

---

internal/cmd/config.go

feat(config): add edit flag

---

internal/actors/actors.go
internal/actors/debug/debug.go
internal/actors/done/done.go
internal/actors/hide/hide.go
internal/actors/pass/pass.go
internal/actors/print/print.go
internal/actors/read/read.go
internal/cmd/list.go
internal/manager/manager.go
internal/views/command/command.go

refactor: use io.Writer in actors

---

go.mod
go.sum
internal/actors/actors.go
internal/actors/open/open.go
internal/gh/enrichments.go
internal/notifications/notifications.go

This pulls the HTML URL from the subject, which allows to open it via the default browser.

feat(actor,notifications): open notification from the subject URL

---

README.md

docs(README): add section about running sync automatically

---

internal/config/config.go
internal/gh/gh.go
internal/manager/manager.go

feat(gh,config): config for all notifications and retry/page count

---

internal/cmd/repl.go
internal/config/config.go
internal/config/keymap.go
internal/views/command/command.go
internal/views/filter/filter.go
internal/views/normal/normal.go

feat(config, repl): configurable keymap

---

internal/cmd/config.go
internal/config/config.go

docs(config): simplify documentation and init flag

---

.github/workflows/ci.yml

The CI won't actually run on this PR, so I will open a new one just after to check if this actually works.

feat(ci): create ci workflow

---

.github/workflows/ci.yml
cmd/gh-not/main.go
internal/gh/gh.go

cc https://go.dev/blog/deadcode
Thanks @chrisgavin for the help 🎉

feat(ci): check for deadcode

---

internal/actors/debug/debug.go
internal/actors/done/done.go
internal/actors/open/open.go
internal/actors/print/print.go
internal/actors/read/read.go
internal/cache/cache.go
internal/cmd/list.go
internal/cmd/repl.go
internal/gh/enrichments.go
internal/manager/manager.go
internal/notifications/view.go
internal/views/normal/normal.go
internal/views/views.go

This makes the view functions a bit simpler.

refactor(log): simplify logging and notification debug rendering

---

internal/gh/enrichments.go

feat(gh): don't enrich Done notifications

---

internal/manager/manager.go

feat(manager): don't apply rules on Done notifications

---

internal/gh/errors.go
internal/gh/gh.go
internal/gh/gh_test.go

feat(gh): protect against all decoding errors

---

internal/cmd/config.go
internal/config/config.go

fix(config): write only config's `data` to disk

---

internal/cmd/list.go
internal/cmd/repl.go
internal/cmd/root.go
internal/cmd/sync.go
internal/logger/logger.go
internal/manager/manager.go

refactor(commands): various small improvements for the commands organization

---

internal/config/rule.go
internal/config/rule_test.go
internal/jq/jq.go
internal/jq/jq_test.go

feat(jq,rule): tests and advanced filters

---

internal/manager/manager.go

fix(manager): rework refresh to run only when necessary

---

internal/gh/gh.go
internal/gh/gh_test.go

fix(gh): paginate the correct number of pages

---

README.md

docs(README): remove old flag for forcing a refresh

---

internal/cmd/sync.go
internal/manager/manager.go

Sometimes it's good to force an apply on the notifications.

feat(sync): add --force flag to apply rules even on Done notifications

---

internal/cache/cache.go
internal/cmd/root.go
internal/cmd/sync.go
internal/manager/manager.go
internal/manager/strategies.go
internal/notifications/sync.go

This ended up to refactor a bunch of other things.

fix(caller): ensure the caller is appropriately defined

---

internal/cmd/sync.go
internal/manager/manager.go

feat: add sync stats and refresh note

---

internal/cmd/root.go
internal/notifications/notifications.go
internal/notifications/view.go

feat: add last updated date

---

.github/workflows/release.yml

E.g. https://github.com/nobe4/gh-not/actions/runs/10027511018/job/27713285629

fix: load go version from mod file

---

internal/cmd/root.go
internal/jq/jq.go
internal/notifications/notifications.go

Also fixed some method's name.
Fix #91

feat(json): add JSON output

---

internal/cmd/root.go

This enable filtering directly by existing rule

feat(root): add --rule flag

---

internal/notifications/notifications_test.go
internal/notifications/sync_test.go

Bug introduced in cf41dbf11a4b5665b0aba12ee2840ad98082d83d

fix(tests): use fixed times to sort on

---

internal/notifications/notifications.go
internal/notifications/sync.go
internal/notifications/sync_test.go

This will enable filtering by wether a notification is still present in the remote.

feat(notifications): add Meta RemoteExists field

---

internal/cmd/root.go
internal/config/rule.go
internal/config/rule_test.go
internal/jq/jq.go
internal/manager/manager.go

refactor(rules): filter directly on notifications

---

internal/actors/done/done.go
internal/actors/open/open.go
internal/cmd/root.go
internal/gh/enrichments.go
internal/notifications/notifications.go
internal/notifications/sync.go
internal/notifications/view.go
internal/views/normal/normal.go

This adds a field in the notification struct that contains the rendered
string to display. This simplifies the handling of notifications and
their display.

feat(notifications): render notifications ahead of time

---

internal/views/normal2/command.go
internal/views/normal2/handlers.go
internal/views/normal2/normal2.go
internal/views/normal2/view.go

refactor(normal): move handlers into separate file

---

internal/views/normal2/handlers.go
internal/views/normal2/keymap.go
internal/views/normal2/normal2.go
internal/views/normal2/view.go

This makes the rendering consistent and simpler to handle.

refactor(normal): use the list help view exclusively

---

go.mod
go.sum
internal/colors/colors.go

refactor(colors): switch to lipgloss

---

internal/gh/enrichments.go
internal/notifications/sync.go
internal/notifications/sync_test.go

feat(sync): reset Meta.Done on newer remote notification

---

internal/notifications/view.go

fix(notifications): use fallback string format

---

.github/workflows/ci.yml
.goreleaser.yaml
cmd/gen-doc/gen-doc.go
cmd/gen-docs/main.go
cmd/gh-not/main.go
internal/actions/debug/debug.go
internal/actions/done/done.go
internal/actions/hide/hide.go
internal/actions/open/open.go
internal/actions/pass/pass.go
internal/actions/print/print.go
internal/actions/read/read.go
internal/cmd/.gitignore
internal/cmd/actions.go

Fix #134 
Kudos to 
- https://blog.carlana.net/post/2021/how-to-use-go-embed/
- https://blog.carlana.net/post/2016-11-27-how-to-use-go-generate/

feat(actions): automatically generate help for the actions

---

internal/api/mock/calls.go
test/integration/001/calls.json
test/integration/001/want.json
test/integration/the_test.go

This allows to requests more than one page

test(integration): add header handling in integration tests

---

internal/repl/handlers.go

fix(repl): Make `None` actually work

---

internal/cache/cache.go
internal/notifications/view.go

Also fix the default cache age, it needs a timezone
Fix #157

fix(view): don't render an empty notifications list

---

internal/actions/open/open.go

This will make the render slightly less confusing

feat(open): add output for open action

---

internal/api/mock/mock.go
internal/gh/enrichments.go
internal/gh/gh_test.go
internal/notifications/notifications.go
internal/notifications/view.go

feat(notification): add LastCommentor field

---

internal/cache/cache.go

This prepares the work to be done for #169, it just adds a wrapping structure that in the future will contain metadata about the cache.

feat: add a cache wrapper

---

internal/repl/handlers.go

This makes sure hidden notifications are excluded from the view.

feat(repl): hide hidden notifications

---

cmd/gen-docs/main.go
internal/actions/actions.go
internal/actions/assign/assign.go
internal/actions/assign/assign_test.go
internal/actions/done/done.go
internal/actions/hide/hide.go
internal/actions/read/read.go

feat(assign): adds a new assign action

---

internal/actions/actions.go
internal/actions/json/json.go

cc https://github.com/nobe4/gh-not/issues/91

feat(json): implement json action for the REPL

---

internal/actions/open/open.go

cc https://github.com/nobe4/gh-not/issues/192

fix(open): don't open if there's no HtmlUrl

---

internal/actions/actions.go
internal/actions/tag/tag.go
internal/actions/tag/tag_test.go
internal/notifications/notifications.go

This add a new action and Meta field. Tags enable logically grouping notifications. In a future PR I'll add the ability to filter them.
cc #197

feat(tag): add tag action

---

README.md
internal/cache/cache.go
internal/cmd/sync.go
internal/config/rule_test.go
internal/manager/manager.go
internal/notifications/sync.go
internal/repl/repl.go
internal/repl/view.go

- **chore: fix typos and style**
- **chore: use synchronization everywhere**

typos suggestion

---

.golangci.yml
internal/actions/actions.go
internal/actions/assign/assign.go
internal/actions/assign/assign_test.go
internal/actions/open/open.go
internal/api/file/file.go
internal/api/github/github.go
internal/api/mock/mock.go
internal/cache/cache.go
internal/cmd/config.go
internal/cmd/root.go
internal/config/config.go
internal/config/path.go
internal/gh/enrichments.go
internal/gh/gh.go
internal/gh/gh_test.go
internal/jq/jq.go
internal/manager/manager.go
internal/manager/strategies.go
internal/notifications/notifications.go
internal/repl/command.go
internal/repl/item.go
internal/repl/repl.go

At this point, most linters are enabled, and properly configured.
More improvements will be done in the future, maybe ™️

chore: enable yet more linters

---

.github/workflows/ci.yml
.golangci.yml
internal/api/mock/mock.go
internal/cache/cache.go
internal/cmd/config.go
internal/cmd/root.go
internal/cmd/sync.go
internal/gh/gh.go
internal/manager/manager.go

fixes https://github.com/nobe4/gh-not/pull/260

fix(lint): migrate and fix golangci-lint

---

.github/workflows/ci.yml

Fix:
- https://github.com/nobe4/gh-not/security/code-scanning/6
- https://github.com/nobe4/gh-not/security/code-scanning/5
- https://github.com/nobe4/gh-not/security/code-scanning/4
- https://github.com/nobe4/gh-not/security/code-scanning/3
- https://github.com/nobe4/gh-not/security/code-scanning/2

fix(ci): add permissions

---

internal/actions/json/json.go
internal/jq/jq.go
internal/notifications/notifications.go

E.g. 
```
:json .url
:json .title
:json .subject
:json .subject.url
```

feat(json): allow to select for a single field from the REPL
