.goreleaser.yaml
internal/cmd/root.go

`gh-not --version` now says something useful

feat: add version in release

---

internal/api/api.go
internal/api/file/file.go
internal/cmd/root.go
internal/gh/gh.go

This provide an on-disk implementation of the API Caller depending on the use. Currently it helps to develop locally while keeping the API requests to a minimum. It's also useful when working offline.
Currently, only the basic "get me all notifications" request is handled, and further implementations will be done when necessary.

feat: create an interface for the API Caller

---

internal/actors/actors.go
internal/actors/debug/debug.go
internal/actors/done/done.go
internal/actors/hide/hide.go
internal/actors/pass/pass.go
internal/actors/print/print.go
internal/actors/read/read.go
internal/api/api.go
internal/cmd/root.go
internal/config/config.go
internal/gh/enrichments.go
internal/gh/gh.go
internal/jq/jq.go
internal/notifications/notifications.go
internal/notifications/notifications_test.go
internal/views/command/command.go
internal/views/normal/normal.go

This enables in-place edit of the notifications in the list and will enable later easier management with a single Notifications instance.
It also replaces the remaining instances of `[]Notification` with `Notifications`.

refactor(notifications): use pointers for Notifications

---

README.md

This PR should clarify how `gh-not` work at a high level.

docs: add a how it works 101 section in the README

---

internal/cmd/root.go
internal/manager/manager.go

This makes the condition for refreshing the cache more explicit.

refactor(manager): rework how the refresh condition is handled

---

.github/workflows/ci.yml

That should be enough, as goreleaser already build for all OS.

feat(ci): run on ubuntu only

---

.goreleaser.yaml
internal/cmd/root.go

```
gh-not version vdev (123abc) built at now
https://github.com/nobe4/gh-not/releases/tag/vdev
```

feat(version): improve version display

---

internal/actors/done/done.go
internal/cmd/list.go
internal/cmd/repl.go
internal/notifications/notifications.go
internal/notifications/sync.go
internal/notifications/sync_test.go
internal/notifications/view.go
internal/notifications/view_test.go

clarify the naming and align the name with the `done` action
BREAKING CHANGE: `Meta.ToDelete` is now `Meta.Done`

refactor(notifications): rename ToDelete to Done

---

internal/views/command/command.go
internal/views/filter/filter.go

This will ensure that even if the configuration is missing a 'command mode' or 'filter mode' key, the program will not fail. This is a temporary fix before #59 gets implemented.

fix(views): add conditional preventing failure on missing config

---

internal/actors/debug/debug.go
internal/actors/done/done.go
internal/actors/read/read.go

This improves the readability of the output.

fix(actors): add space after the actor's verb

---

.github/workflows/ci.yml
.gitignore
internal/api/api.go
internal/api/github/github.go
internal/api/mock/mock.go
internal/cmd/root.go
internal/gh/enrichments.go
internal/gh/errors.go
internal/gh/errors_test.go
internal/gh/gh.go
internal/gh/gh_test.go
script/watch-test

tests(gh): write some tests around HTTP handling

---

internal/cmd/repl.go
internal/config/config.go
internal/config/defaults.go
internal/views/normal/normal.go

Fix #62 
`view.height` isn't a totally correct name, as the view will always be height + 1 (for the prompt).
This will cause issues if the height is small, or even set to 0. The help toggle might expand the view.
But I'll deal with that another time.

feat(view): fixed size view

---

internal/config/config.go
internal/config/rule.go

Some keys didn't unmarshal correctly, this was due to a lack of understanding of how mapstructure works. Leaving `yaml:...` is incorrect and should be replaced by `mapstructure:...` instead.
It's a bit confusing, but fixes the configuration unmarshal'ing now.
See
- https://github.com/spf13/viper/blob/master/TROUBLESHOOTING.md#unmarshaling-doesnt-work
- https://github.com/spf13/viper/issues/498#issuecomment-1354902927
- https://github.com/spf13/viper/issues/498#issuecomment-410485531

fix(config): struct annotation correction

---

internal/cmd/repl.go
internal/cmd/root.go
internal/cmd/sync.go

Only `sync` and `repl` modify the notification list, so only those commands need to save the cache after.
Fix #89

fix(cmd): run manager.save only on commands that load and change it

---

internal/config/rule_test.go
internal/jq/jq_test.go

`and`, `or` and `()` influence the order of operations, this makes explicit the different cases.
cc #86

test(config,jq): add more tests to make explicit the order of operations

---

internal/config/config.go
internal/config/rule.go
internal/jq/jq.go
internal/jq/jq_test.go

This caches during the config parsing any invalid JQ filter. 
cc #86
Thanks @grantbirki for the help debugging this.

feat(config, jq): add rule testing during config parsing

---

.goreleaser.yaml
README.md
internal/cmd/root.go
internal/version/version.go

Starting in 1.18, git information is stored in the binary, it's possible to pull it at runtime. Using the runtime/debug package, we can extract the `commit` and `date` information.
The `version` (renamed `tag`) still comes from the ldflags. This allows for simpler build/install process.
- https://pkg.go.dev/runtime/debug@go1.22.5#ReadBuildInfo
- https://icinga.com/blog/2022/05/25/embedding-git-commit-information-in-go-binaries/
Thanks @natefinch, @chrisgavin, @cogswell for the help.
Fix #95

feat(build): simplify build/install process by pulling debug info

---

internal/gh/gh.go
internal/manager/manager.go

The logic to ignore done notifications was moot given that it ran on notifications not yet sync'ed. This meant the `Meta.Done` field was _always_ set to `false`.
This change moves the enrichment after the sync between the API and cached notifications, at which point the `Meta` will exist.
Fix https://github.com/nobe4/gh-not/issues/98

fix: only enrich non-done notifications

---

internal/cmd/root.go
internal/logger/logger.go
internal/views/views.go

Because bubbletea occupies STDERR/STDOUT, the logging needs to happen in a different place. When `--repl` is set, all logs will go to /tmp/gh-not-debug.log.

feat(views): implement logging for bubbletea interface

---

internal/actors/hide/hide.go
internal/notifications/sync.go
internal/notifications/sync_test.go

The hidden state now will remove the notification from the cache when it is removed from the API.
Fix https://github.com/nobe4/gh-not/issues/138

feat(hide): rework hidden state

---

internal/actions/done/done.go
internal/actions/read/read.go
internal/api/api.go
internal/api/file/file.go
internal/api/github/github.go
internal/api/mock/mock.go
internal/cmd/sync.go
internal/gh/enrichments.go
internal/gh/gh.go
internal/gh/gh_test.go
internal/jq/jq_test.go
internal/manager/manager.go

This shifts the responsibility to unmarshal to the caller of `Request`.

refactor(api): drop `Do` method in the `Requestor` interface

---

internal/cache/cache.go
internal/cmd/root.go
internal/manager/manager.go

This allows the manager to access the cache's age for display purpose. It enables the user to reason about when the cache was last refreshed and if a new refresh is needed.

feat(cache): get the refreshed date

---

internal/repl/browser.go

Before, it was selecting from all items, but now it only selects from visible items.

fix(repl): select all only works on filtered items

---

internal/api/mock/calls.go
internal/api/mock/mock.go
internal/gh/enrichments.go
internal/notifications/notifications.go
internal/notifications/sync.go
test/integration/001/calls.json
test/integration/002/cache.json
test/integration/002/calls.json
test/integration/002/want.json
test/integration/the_test.go

Add other improvements and another integration test.

test(integration): add error handling for responses

---

.github/workflows/ci.yml
internal/jq/jq_test.go

The current CI test fails to correctly report the failure to GitHub action, `column` eats the status code:
```shell
$ go test -v -cover ./...                   
internal/cmd/actions.go:9:12: pattern actions-help.txt: no matching files found
$ echo $?
1
$ go test -v -cover ./... | column -t -s'  '
internal/cmd/actions.go:9:12: pattern actions-help.txt: no matching files found
$ echo $?
0
```
E.g. https://github.com/nobe4/gh-not/actions/runs/10861497487/job/30143462753?pr=167

test: fix CI tests

---

internal/api/file/file.go
internal/api/mock/calls.go
internal/api/mock/mock.go
internal/config/config.go
internal/config/defaults.go
internal/gh/errors.go
internal/gh/errors_test.go
internal/gh/gh.go
internal/gh/gh_test.go

This also refactors the `defaultEndpoint` to use a full URL.
Fix #171

feat(gh): add `per_page` parameter for API calls

---

internal/cache/cache.go
internal/manager/manager.go

This removes the need for using the FS information when checking when
the cache has been last refreshed. Calling `SetRefreshedAt` will
manually update this value before saving it.
cc https://github.com/nobe4/gh-not/issues/169

feat(cache): store RefreshedAt information in the Wrapper

---

internal/cache/cache.go
internal/gh/gh.go
internal/manager/manager.go

This closes the loop on #169 by moving the expiration logic into the manager instead of in the cache. While the cache's configuration conserves the `ttl_in_hours`, the logic is now handled in the manager. This simplifies the cache to implement just a RefreshReadWriter.

feat(cache): move the expiration logic out

---

internal/cache/cache.go

Fix case when cache is missing and `wrap` is nil.
```
$ go run cmd/gh-not/main.go -c config.local.yaml -v4
time=2024-09-29T20:11:08.443+02:00 level=DEBUG msg="loading configuration" path=config.local.yaml
time=2024-09-29T20:11:08.443+02:00 level=DEBUG msg="loading default configuration"
time=2024-09-29T20:11:08.443+02:00 level=DEBUG msg="setting config name and path" path=config.local.yaml
time=2024-09-29T20:11:08.444+02:00 level=DEBUG msg="cache doesn't exist" path=./cache-test.json
time=2024-09-29T20:11:08.444+02:00 level=INFO msg="Loaded notifications" count=0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x1044e8964]
goroutine 1 [running]: …
```

fix(cache): catch nil wrap expiration date

---

internal/cache/cache.go

This ensures that the RefreshedAt is set when the cache is defined. That simplifies (and fixes) reading/writing to the RefreshedAt field.

fix(cache): initialize the wrapper explicitly

---

go.mod
go.sum
internal/repl/browser.go
internal/repl/handlers.go
internal/repl/item.go
internal/repl/repl.go

After battling against bubble's incomplete interface, I've decided to store the list's index manually and do the logic myself.
The indexes are computed each time the list change size (i.e. after executing a command) and used whenever changing an item is necessary.
This prevent the list of items from being replaced during selecting all as described in https://github.com/nobe4/gh-not/issues/175#issuecomment-2381476328
It removes the dependency on https://github.com/charmbracelet/bubbles/pull/574.
Fix #175

fix(repl): items store their index in the list

---

internal/repl/command.go

- if the command is fully typed: the behavior doesn't change
- if the command is partially typed: the suggestion is used

feat(command): use suggestion's text for command

---

internal/actions/actions.go
internal/actions/debug/debug.go
internal/actions/done/done.go
internal/actions/hide/hide.go
internal/actions/open/open.go
internal/actions/pass/pass.go
internal/actions/print/print.go
internal/actions/read/read.go
internal/manager/manager.go
internal/repl/command.go
internal/repl/handlers.go
internal/repl/repl.go

This prepares later work for #187. Passing parameter will enable additional customization in the REPL and later in the config as well.
Only the `Debug` action currently uses this new parameter, to confirm it's receiving it correctly.
Also have to do some workaround a bubble limitation, see https://github.com/charmbracelet/bubbles/pull/630

feat(actions): allow passing string parameters to actions

---

internal/config/rule.go
internal/manager/manager.go

This build on #188 and allow to specify arguments in the rules.
E.g.
```yaml
rules:
- name: test
action: debug
args: ["a", "b"]
```
cc #187

feat(config): enable passing arguments to the rule

---

internal/actions/assign/assign.go
internal/actions/tag/tag.go
internal/cmd/root.go
internal/notifications/view.go

This adds two new flags to the root command:
- `--tags` shows a summary of the tags
- `--tag X` filter notifications by the tag `X`
Fix #197

feat(root): display tags and filter by tag

---

internal/manager/manager.go

If any notification fails to enrich, it should not prevent the others from continuing being enriched as well.

fix(manager): relax enrichment failure

---

README.md

Remove the `go install` method which won't work because of the dependency on `go generate ./...`.
Fix #206

docs(README): simplify the installation methods

---

internal/gh/gh.go

This helps to get a sense of why a request is failing and why it's retrying.

feat(gh): add error information in the output

---

internal/gh/enrichments.go
internal/notifications/notifications.go

This PR adds assignees, reviewers, and review teams to be able to filter on them
For assignees and reviewers it's just a list of Users and for review teams I add the Team struct and have list of those. 
Fixes #200

Add Assignees, Reviewers and ReviewersTeams

---

internal/cmd/config.go
internal/config/config.go

Fixes #223
- Fixing how the error is compared if viper can't read the config
- Exposing the initial path for new config
- Creating the config folder if it doesn't exist
Closes #224 (thanks tho for the effort @ccoVeille :pray:)

fix(config): init bootstrap the config folder

---

.github/workflows/ci.yml
.golangci.yml

Currently 43 errors, more rules could be enabled.
But let's start with these ones.
Fixes:
- #221

ci: enable golangci-lint

---

.golangci.yml
internal/cache/cache.go
internal/cmd/actions.go
internal/cmd/config.go
internal/cmd/root.go
internal/cmd/sync.go
internal/config/keymap.go
internal/gh/gh.go
internal/gh/gh_test.go
internal/manager/manager.go
internal/manager/strategies.go
internal/notifications/notifications.go
internal/notifications/sync.go
internal/repl/command.go
internal/repl/handlers.go
internal/repl/view.go

This refactors the config to eventually allow all linters. In order to simplify the fixing work, the linters will be manually added one at a time in later PRs, and/or commented as to why they are left unused.
Closes https://github.com/nobe4/gh-not/pull/228

feat: enable all golangci-lint linters

---

README.md
internal/api/api.go
internal/api/file/file.go
internal/cache/cache.go
internal/gh/gh.go
internal/gh/gh_test.go
test/integration/000/calls.json
test/integration/001/calls.json
test/integration/002/calls.json

This PR attempts to bring multi-host capabilities in `gh-not`.
It removes the hardcoded default URL and instead relies on `go-gh` self-discovery mechanism.
The `Request` doesn't actually need a full URL; a path is enough: https://github.com/cli/go-gh/blob/13104ed7b2db4b8c1a83de4248ddfaaab7682916/pkg/api/rest_client.go#L75-L77
It also builds the full REST URL dynamically: https://github.com/cli/go-gh/blob/13104ed7b2db4b8c1a83de4248ddfaaab7682916/pkg/api/rest_client.go#L153-L172
The way to use it is similar to what `gh` expect. E.g. for ghe.io:
```shell
GH_DEBUG=api \
GH_HOST=ghe.io \
go run ./cmd/gh-not/main.go -c config.gheio.yaml -v4 sync -r force
GH_DEBUG=api \
GH_HOST=ghe.io \
GH_ENTERPRISE_TOKEN=[REDACTED] \
go run ./cmd/gh-not/main.go -c config.gheio.yaml -v4 sync -r force
```
⚠️ …

feat(gh): allow multiple hosts

---

README.md
internal/version/version.go

Requested by @tebriel, to build the binary with custom information.
This takes the approach of ignoring the debug info if any of the default value is changed.
e.g.
$ go build --ldflags="-w -s" ./cmd/gh-not && ./gh-not --version
gh-not version v0.6.1+dirty (92248254838460978b3af005c350eba3463050b9) built at 2025-02-14T18:41:31Z
https://github.com/nobe4/gh-not/releases/tag/v0.6.1+dirty
$ go build --ldflags="-w -s -X github.com/nobe4/gh-not/internal/version.tag=0.1.0" ./cmd/gh-not && ./gh-not --version
gh-not version 0.1.0 (UNSET_COMMIT) built at UNSET_DATE
https://github.com/nobe4/gh-not/releases/tag/0.1.0

feat(version): allow custom build info

---

internal/config/config.go
internal/config/path.go
internal/config/path_test.go
script/watch-test

This technically allows for any environment variable to be part of the config or cache path. So $HOME, $XDG_CONFIG_HOME, etc., can be used.
This was raised in #247 and will work nicely with the forbidding of `~`.
cc #246
E.g.
```shell
$ go run cmd/gh-not/main.go --config=~/.config/gh-not/config.yaml
...
failed to execute the root command: failed to load the config: failed to expand config path: tilde in path is not supported, use $HOME instead: ~/.config/gh-not/config.yaml
exit status 1
$ go run cmd/gh-not/main.go                                      
...
failed to execute the root command: failed to load the config: failed to expand cache path: tilde in path is not supported, use $HOME instead: ~/.local/state/gh-not/cache.json
exit status 1
```

feat(config): enable $ENVIRONMENT-based path

---

internal/repl/handlers.go

This fixes the REPL printing a new line and breaking its display. 
The only useful output from this action is the confirmation that the notification was opened, so we can just ignore it when we open a single one.

fix(repl): discard all output for `open` command

---

internal/actions/open/open.go

This will enable using `GH_BROWSER=echo` without the api/html URL being jammed together.
Before:
```
OPEN https://api.github.com/repos/X/Y/pulls/Zhttps://github.com/X/Y/pull/Z
```
After:
```
OPEN https://api.github.com/repos/X/Y/pulls/Z https://github.com/X/Y/pull/Z
```

fix(open): add separating space

---

internal/cmd/root.go
internal/config/config.go
internal/config/defaults.go

The XDG specification proposes log files for user apps [go in the state directory](https://specifications.freedesktop.org/basedir-spec/latest/index.html#variables). I've made it configurable (but updated the default location).
This log file is currently only used for the REPL so I put it with the height config in the View Struct.

chore(view.log_file): use XDG_STATE_DIR as default repl log location
